<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN322797" failures="1" tests="5" name="Default test" time="13.729" errors="0" timestamp="2023-11-13T08:22:14 IST">
  <testcase classname="Test.testStartToEnd" name="loginToApp" time="5.739"/>
  <testcase classname="Test.testStartToEnd" name="addItemToCart" time="3.356"/>
  <testcase classname="Test.testStartToEnd" name="checkout" time="0.187"/>
  <testcase classname="Test.testStartToEnd" name="placeOrder" time="0.002">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void Test.testStartToEnd.placeOrder()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: placeOrder([])
Arguments: [(java.util.HashMap) {searchProduct=ADIDAS ORIGINAL, pass=9760pks, email=9760pks@gmail.com}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Test.testStartToEnd.placeOrder()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: placeOrder([])
Arguments: [(java.util.HashMap) {searchProduct=ADIDAS ORIGINAL, pass=9760pks, email=9760pks@gmail.com}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- placeOrder -->
  <testcase classname="Test.testStartToEnd" name="checkOrder" time="0.162"/>
</testsuite> <!-- Default test -->
